version: "3.3"
services:
   database:
      image: mysql:5.7
      ports:
         - "3306:3306"
      volumes:
         - ./volumenes/mysql:/var/lib/mysql
         - ./dockerfiles/php/Sistema-PHP-POO/bd/sistema_php_poo.sql:/docker-entrypoint-initdb.d/dump.sql
      env_file:
         - ./.env
      networks:
         app_net:
            ipv4_address: 192.168.20.10
   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
         - database:mysql
      ports:
         - "8181:80"
      env_file:
         - ./.env
      networks:
         app_net:
            ipv4_address: 192.168.20.11
   web:
      build: ./dockerfiles/php/
      depends_on:
         - database
      links:
         - database:mysql
         - mailcatcher
      ports:
         - "8080:80"
      volumes:
         - ./dockerfiles/php/Sistema-PHP-POO/:/var/www/html
      env_file:
         - ./.env
      networks:
         app_net:
            ipv4_address: 192.168.20.12
   mailcatcher:
      image: schickling/mailcatcher
      ports:
         - "1025:1025"
         - "1080:1080"
      environment:
         MAILCATCHER_PORT: 1025
      networks:
         app_net:
            ipv4_address: 192.168.20.13
networks:
   app_net:
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 192.168.20.0/24